import { css } from 'solid-styled-components';

import { CSSProperties, PseudosObject, Pseudos } from './css-properties';

interface Props {
  styling?: CSSProperties;
  pseudos?: PseudosObject;
}

export function createClass({ styling, pseudos }: Props) {
  const currentClass = css`
    ${createCss(styling)}
    ${createPseudos(pseudos)}
  `;

  return currentClass;
}

function createCss(styling?: CSSProperties) {
  if (!styling) return '';

  return `
    ${cssHelper('accent-color', styling.accentColor)}
    ${cssHelper('align-content', styling.alignContent)}
    ${cssHelper('align-items', styling.alignItems)}
    ${cssHelper('align-self', styling.alignSelf)}
    ${cssHelper('align-tracks', styling.alignTracks)}
    ${cssHelper('animation-delay', styling.animationDelay)}
    ${cssHelper('animation-direction', styling.animationDirection)}
    ${cssHelper('animation-duration', styling.animationDuration)}
    ${cssHelper('animation-fill-mode', styling.animationFillMode)}
    ${cssHelper('animation-iteration-count', styling.animationIterationCount)}
    ${cssHelper('animation-name', styling.animationName)}
    ${cssHelper('animation-play-state', styling.animationPlayState)}
    ${cssHelper('animation-timing-function', styling.animationTimingFunction)}
    ${cssHelper('appearance', styling.appearance)}
    ${cssHelper('aspect-ratio', styling.aspectRatio)}
    ${cssHelper('backdrop-filter', styling.backdropFilter)}
    ${cssHelper('backface-visibility', styling.backfaceVisibility)}
    ${cssHelper('background-attachment', styling.backgroundAttachment)}
    ${cssHelper('background-blend-mode', styling.backgroundBlendMode)}
    ${cssHelper('background-clip', styling.backgroundClip)}
    ${cssHelper('background-color', styling.backgroundColor)}
    ${cssHelper('background-image', styling.backgroundImage)}
    ${cssHelper('background-origin', styling.backgroundOrigin)}
    ${cssHelper('background-position-x', styling.backgroundPositionX)}
    ${cssHelper('background-position-y', styling.backgroundPositionY)}
    ${cssHelper('background-repeat', styling.backgroundRepeat)}
    ${cssHelper('background-size', styling.backgroundSize)}
    ${cssHelper('block-overflow', styling.blockOverflow)}
    ${cssHelper('block-size', styling.blockSize)}
    ${cssHelper('border-block-color', styling.borderBlockColor)}
    ${cssHelper('border-block-end-color', styling.borderBlockEndColor)}
    ${cssHelper('border-block-end-style', styling.borderBlockEndStyle)}
    ${cssHelper('border-block-end-width', styling.borderBlockEndWidth)}
    ${cssHelper('border-block-start-color', styling.borderBlockStartColor)}
    ${cssHelper('border-block-start-style', styling.borderBlockStartStyle)}
    ${cssHelper('border-block-start-width', styling.borderBlockStartWidth)}
    ${cssHelper('border-block-style', styling.borderBlockStyle)}
    ${cssHelper('border-block-width', styling.borderBlockWidth)}
    ${cssHelper('border-bottom-color', styling.borderBottomColor)}
    ${cssHelper('border-bottom-left-radius', styling.borderBottomLeftRadius)}
    ${cssHelper('border-bottom-right-radius', styling.borderBottomRightRadius)}
    ${cssHelper('border-bottom-style', styling.borderBottomStyle)}
    ${cssHelper('border-bottom-width', styling.borderBottomWidth)}
    ${cssHelper('border-collapse', styling.borderCollapse)}
    ${cssHelper('border-end-end-radius', styling.borderEndEndRadius)}
    ${cssHelper('border-end-start-radius', styling.borderEndStartRadius)}
    ${cssHelper('border-image-outset', styling.borderImageOutset)}
    ${cssHelper('border-image-repeat', styling.borderImageRepeat)}
    ${cssHelper('border-image-slice', styling.borderImageSlice)}
    ${cssHelper('border-image-source', styling.borderImageSource)}
    ${cssHelper('border-image-width', styling.borderImageWidth)}
    ${cssHelper('border-inline-color', styling.borderInlineColor)}
    ${cssHelper('border-inline-end-color', styling.borderInlineEndColor)}
    ${cssHelper('border-inline-end-style', styling.borderInlineEndStyle)}
    ${cssHelper('border-inline-end-width', styling.borderInlineEndWidth)}
    ${cssHelper('border-inline-start-color', styling.borderInlineStartColor)}
    ${cssHelper('border-inline-start-style', styling.borderInlineStartStyle)}
    ${cssHelper('border-inline-start-width', styling.borderInlineStartWidth)}
    ${cssHelper('border-inline-style', styling.borderInlineStyle)}
    ${cssHelper('border-inline-width', styling.borderInlineWidth)}
    ${cssHelper('border-left-color', styling.borderLeftColor)}
    ${cssHelper('border-left-style', styling.borderLeftStyle)}
    ${cssHelper('border-left-width', styling.borderLeftWidth)}
    ${cssHelper('border-right-color', styling.borderRightColor)}
    ${cssHelper('border-right-style', styling.borderRightStyle)}
    ${cssHelper('border-right-width', styling.borderRightWidth)}
    ${cssHelper('border-spacing', styling.borderSpacing)}
    ${cssHelper('border-start-end-radius', styling.borderStartEndRadius)}
    ${cssHelper('border-start-start-radius', styling.borderStartStartRadius)}
    ${cssHelper('border-top-color', styling.borderTopColor)}
    ${cssHelper('border-top-left-radius', styling.borderTopLeftRadius)}
    ${cssHelper('border-top-right-radius', styling.borderTopRightRadius)}
    ${cssHelper('border-top-style', styling.borderTopStyle)}
    ${cssHelper('border-top-width', styling.borderTopWidth)}
    ${cssHelper('bottom', styling.bottom)}
    ${cssHelper('box-decoration-break', styling.boxDecorationBreak)}
    ${cssHelper('box-shadow', styling.boxShadow)}
    ${cssHelper('box-sizing', styling.boxSizing)}
    ${cssHelper('break-after', styling.breakAfter)}
    ${cssHelper('break-before', styling.breakBefore)}
    ${cssHelper('break-inside', styling.breakInside)}
    ${cssHelper('caption-side', styling.captionSide)}
    ${cssHelper('caret-color', styling.caretColor)}
    ${cssHelper('clear', styling.clear)}
    ${cssHelper('clip-path', styling.clipPath)}
    ${cssHelper('color', styling.color)}
    ${cssHelper('color-adjust', styling.colorAdjust)}
    ${cssHelper('color-scheme', styling.colorScheme)}
    ${cssHelper('column-count', styling.columnCount)}
    ${cssHelper('column-fill', styling.columnFill)}
    ${cssHelper('column-gap', styling.columnGap)}
    ${cssHelper('column-rule-color', styling.columnRuleColor)}
    ${cssHelper('column-rule-style', styling.columnRuleStyle)}
    ${cssHelper('column-rule-width', styling.columnRuleWidth)}
    ${cssHelper('column-span', styling.columnSpan)}
    ${cssHelper('column-width', styling.columnWidth)}
    ${cssHelper('contain', styling.contain)}
    ${cssHelper('content', styling.content)}
    ${cssHelper('content-visibility', styling.contentVisibility)}
    ${cssHelper('counter-increment', styling.counterIncrement)}
    ${cssHelper('counter-reset', styling.counterReset)}
    ${cssHelper('counter-set', styling.counterSet)}
    ${cssHelper('cursor', styling.cursor)}
    ${cssHelper('direction', styling.direction)}
    ${cssHelper('display', styling.display)}
    ${cssHelper('empty-cells', styling.emptyCells)}
    ${cssHelper('filter', styling.filter)}
    ${cssHelper('flex-basis', styling.flexBasis)}
    ${cssHelper('flex-direction', styling.flexDirection)}
    ${cssHelper('flex-grow', styling.flexGrow)}
    ${cssHelper('flex-shrink', styling.flexShrink)}
    ${cssHelper('flex-wrap', styling.flexWrap)}
    ${cssHelper('float', styling.float)}
    ${cssHelper('font-family', styling.fontFamily)}
    ${cssHelper('font-feature-settings', styling.fontFeatureSettings)}
    ${cssHelper('font-kerning', styling.fontKerning)}
    ${cssHelper('font-language-override', styling.fontLanguageOverride)}
    ${cssHelper('font-optical-sizing', styling.fontOpticalSizing)}
    ${cssHelper('font-size', styling.fontSize)}
    ${cssHelper('font-size-adjust', styling.fontSizeAdjust)}
    ${cssHelper('font-smooth', styling.fontSmooth)}
    ${cssHelper('font-stretch', styling.fontStretch)}
    ${cssHelper('font-style', styling.fontStyle)}
    ${cssHelper('font-synthesis', styling.fontSynthesis)}
    ${cssHelper('font-variant', styling.fontVariant)}
    ${cssHelper('font-variant-caps', styling.fontVariantCaps)}
    ${cssHelper('font-variant-east-asian', styling.fontVariantEastAsian)}
    ${cssHelper('font-variant-ligatures', styling.fontVariantLigatures)}
    ${cssHelper('font-variant-numeric', styling.fontVariantNumeric)}
    ${cssHelper('font-variant-position', styling.fontVariantPosition)}
    ${cssHelper('font-variation-settings', styling.fontVariationSettings)}
    ${cssHelper('font-weight', styling.fontWeight)}
    ${cssHelper('forced-color-adjust', styling.forcedColorAdjust)}
    ${cssHelper('grid-aut-o-columns', styling.gridAutoColumns)}
    ${cssHelper('grid-aut-o-flow', styling.gridAutoFlow)}
    ${cssHelper('grid-aut-o-rows', styling.gridAutoRows)}
    ${cssHelper('grid-column-end', styling.gridColumnEnd)}
    ${cssHelper('grid-column-start', styling.gridColumnStart)}
    ${cssHelper('grid-row-end', styling.gridRowEnd)}
    ${cssHelper('grid-row-start', styling.gridRowStart)}
    ${cssHelper('grid-template-areas', styling.gridTemplateAreas)}
    ${cssHelper('grid-template-columns', styling.gridTemplateColumns)}
    ${cssHelper('grid-template-rows', styling.gridTemplateRows)}
    ${cssHelper('hanging-punctuation', styling.hangingPunctuation)}
    ${cssHelper('height', styling.height)}
    ${cssHelper('hyphens', styling.hyphens)}
    ${cssHelper('image-orientation', styling.imageOrientation)}
    ${cssHelper('image-rendering', styling.imageRendering)}
    ${cssHelper('image-resolution', styling.imageResolution)}
    ${cssHelper('initial-letter', styling.initialLetter)}
    ${cssHelper('inline-size', styling.inlineSize)}
    ${cssHelper('inset', styling.inset)}
    ${cssHelper('inset-block', styling.insetBlock)}
    ${cssHelper('inset-block-end', styling.insetBlockEnd)}
    ${cssHelper('inset-block-start', styling.insetBlockStart)}
    ${cssHelper('inset-inline', styling.insetInline)}
    ${cssHelper('inset-inline-end', styling.insetInlineEnd)}
    ${cssHelper('inset-inline-start', styling.insetInlineStart)}
    ${cssHelper('isolation', styling.isolation)}
    ${cssHelper('justify-content', styling.justifyContent)}
    ${cssHelper('justify-items', styling.justifyItems)}
    ${cssHelper('justify-self', styling.justifySelf)}
    ${cssHelper('justify-tracks', styling.justifyTracks)}
    ${cssHelper('left', styling.left)}
    ${cssHelper('letter-spacing', styling.letterSpacing)}
    ${cssHelper('line-break', styling.lineBreak)}
    ${cssHelper('line-height', styling.lineHeight)}
    ${cssHelper('line-height-step', styling.lineHeightStep)}
    ${cssHelper('list-style-image', styling.listStyleImage)}
    ${cssHelper('list-style-position', styling.listStylePosition)}
    ${cssHelper('list-style-type', styling.listStyleType)}
    ${cssHelper('margin-block', styling.marginBlock)}
    ${cssHelper('margin-block-end', styling.marginBlockEnd)}
    ${cssHelper('margin-block-start', styling.marginBlockStart)}
    ${cssHelper('margin-bottom', styling.marginBottom)}
    ${cssHelper('margin-inline', styling.marginInline)}
    ${cssHelper('margin-inline-end', styling.marginInlineEnd)}
    ${cssHelper('margin-inline-start', styling.marginInlineStart)}
    ${cssHelper('margin-left', styling.marginLeft)}
    ${cssHelper('margin-right', styling.marginRight)}
    ${cssHelper('margin-top', styling.marginTop)}
    ${cssHelper('mask-border-mode', styling.maskBorderMode)}
    ${cssHelper('mask-border-outset', styling.maskBorderOutset)}
    ${cssHelper('mask-border-repeat', styling.maskBorderRepeat)}
    ${cssHelper('mask-border-slice', styling.maskBorderSlice)}
    ${cssHelper('mask-border-source', styling.maskBorderSource)}
    ${cssHelper('mask-border-width', styling.maskBorderWidth)}
    ${cssHelper('mask-clip', styling.maskClip)}
    ${cssHelper('mask-composite', styling.maskComposite)}
    ${cssHelper('mask-image', styling.maskImage)}
    ${cssHelper('mask-mode', styling.maskMode)}
    ${cssHelper('mask-origin', styling.maskOrigin)}
    ${cssHelper('mask-position', styling.maskPosition)}
    ${cssHelper('mask-repeat', styling.maskRepeat)}
    ${cssHelper('mask-size', styling.maskSize)}
    ${cssHelper('mask-type', styling.maskType)}
    ${cssHelper('math-style', styling.mathStyle)}
    ${cssHelper('max-block-size', styling.maxBlockSize)}
    ${cssHelper('max-height', styling.maxHeight)}
    ${cssHelper('max-inline-size', styling.maxInlineSize)}
    ${cssHelper('max-lines', styling.maxLines)}
    ${cssHelper('max-width', styling.maxWidth)}
    ${cssHelper('min-block-size', styling.minBlockSize)}
    ${cssHelper('min-height', styling.minHeight)}
    ${cssHelper('min-inline-size', styling.minInlineSize)}
    ${cssHelper('min-width', styling.minWidth)}
    ${cssHelper('mix-blend-mode', styling.mixBlendMode)}
    ${cssHelper('motion-distance', styling.motionDistance)}
    ${cssHelper('motion-path', styling.motionPath)}
    ${cssHelper('motion-rotation', styling.motionRotation)}
    ${cssHelper('object-fit', styling.objectFit)}
    ${cssHelper('object-position', styling.objectPosition)}
    ${cssHelper('offset-anchor', styling.offsetAnchor)}
    ${cssHelper('offset-distance', styling.offsetDistance)}
    ${cssHelper('offset-path', styling.offsetPath)}
    ${cssHelper('offset-rotate', styling.offsetRotate)}
    ${cssHelper('offset-rotation', styling.offsetRotation)}
    ${cssHelper('opacity', styling.opacity)}
    ${cssHelper('order', styling.order)}
    ${cssHelper('orphans', styling.orphans)}
    ${cssHelper('outline-color', styling.outlineColor)}
    ${cssHelper('outline-offset', styling.outlineOffset)}
    ${cssHelper('outline-style', styling.outlineStyle)}
    ${cssHelper('outline-width', styling.outlineWidth)}
    ${cssHelper('overflow-anchor', styling.overflowAnchor)}
    ${cssHelper('overflow-block', styling.overflowBlock)}
    ${cssHelper('overflow-clip-box', styling.overflowClipBox)}
    ${cssHelper('overflow-clip-margin', styling.overflowClipMargin)}
    ${cssHelper('overflow-inline', styling.overflowInline)}
    ${cssHelper('overflow-wrap', styling.overflowWrap)}
    ${cssHelper('overflow-x', styling.overflowX)}
    ${cssHelper('overflow-y', styling.overflowY)}
    ${cssHelper('overscroll-behavior-block', styling.overscrollBehaviorBlock)}
    ${cssHelper('overscroll-behavior-inline', styling.overscrollBehaviorInline)}
    ${cssHelper('overscroll-behavior-x', styling.overscrollBehaviorX)}
    ${cssHelper('overscroll-behavior-y', styling.overscrollBehaviorY)}
    ${cssHelper('padding-block', styling.paddingBlock)}
    ${cssHelper('padding-block-end', styling.paddingBlockEnd)}
    ${cssHelper('padding-block-start', styling.paddingBlockStart)}
    ${cssHelper('padding-bottom', styling.paddingBottom)}
    ${cssHelper('padding-inline', styling.paddingInline)}
    ${cssHelper('padding-inline-end', styling.paddingInlineEnd)}
    ${cssHelper('padding-inline-start', styling.paddingInlineStart)}
    ${cssHelper('padding-left', styling.paddingLeft)}
    ${cssHelper('padding-right', styling.paddingRight)}
    ${cssHelper('padding-top', styling.paddingTop)}
    ${cssHelper('page-break-after', styling.pageBreakAfter)}
    ${cssHelper('page-break-before', styling.pageBreakBefore)}
    ${cssHelper('page-break-inside', styling.pageBreakInside)}
    ${cssHelper('paint-order', styling.paintOrder)}
    ${cssHelper('perspective', styling.perspective)}
    ${cssHelper('perspective-origin', styling.perspectiveOrigin)}
    ${cssHelper('place-content', styling.placeContent)}
    ${cssHelper('pointer-events', styling.pointerEvents)}
    ${cssHelper('position', styling.position)}
    ${cssHelper('quotes', styling.quotes)}
    ${cssHelper('resize', styling.resize)}
    ${cssHelper('right', styling.right)}
    ${cssHelper('rotate', styling.rotate)}
    ${cssHelper('row-gap', styling.rowGap)}
    ${cssHelper('ruby-align', styling.rubyAlign)}
    ${cssHelper('ruby-merge', styling.rubyMerge)}
    ${cssHelper('ruby-position', styling.rubyPosition)}
    ${cssHelper('scale', styling.scale)}
    ${cssHelper('scroll-behavior', styling.scrollBehavior)}
    ${cssHelper('scroll-margin', styling.scrollMargin)}
    ${cssHelper('scroll-margin-block', styling.scrollMarginBlock)}
    ${cssHelper('scroll-margin-block-end', styling.scrollMarginBlockEnd)}
    ${cssHelper('scroll-margin-block-start', styling.scrollMarginBlockStart)}
    ${cssHelper('scroll-margin-bottom', styling.scrollMarginBottom)}
    ${cssHelper('scroll-margin-inline', styling.scrollMarginInline)}
    ${cssHelper('scroll-margin-inline-end', styling.scrollMarginInlineEnd)}
    ${cssHelper('scroll-margin-inline-start', styling.scrollMarginInlineStart)}
    ${cssHelper('scroll-margin-left', styling.scrollMarginLeft)}
    ${cssHelper('scroll-margin-right', styling.scrollMarginRight)}
    ${cssHelper('scroll-margin-top', styling.scrollMarginTop)}
    ${cssHelper('scroll-padding', styling.scrollPadding)}
    ${cssHelper('scroll-padding-block', styling.scrollPaddingBlock)}
    ${cssHelper('scroll-padding-block-end', styling.scrollPaddingBlockEnd)}
    ${cssHelper('scroll-padding-block-start', styling.scrollPaddingBlockStart)}
    ${cssHelper('scroll-padding-bottom', styling.scrollPaddingBottom)}
    ${cssHelper('scroll-padding-inline', styling.scrollPaddingInline)}
    ${cssHelper('scroll-padding-inline-end', styling.scrollPaddingInlineEnd)}
    ${cssHelper('scroll-padding-inline-start', styling.scrollPaddingInlineStart)}
    ${cssHelper('scroll-padding-left', styling.scrollPaddingLeft)}
    ${cssHelper('scroll-padding-right', styling.scrollPaddingRight)}
    ${cssHelper('scroll-padding-top', styling.scrollPaddingTop)}
    ${cssHelper('scroll-snap-align', styling.scrollSnapAlign)}
    ${cssHelper('scroll-snap-margin', styling.scrollSnapMargin)}
    ${cssHelper('scroll-snap-margin-bottom', styling.scrollSnapMarginBottom)}
    ${cssHelper('scroll-snap-margin-left', styling.scrollSnapMarginLeft)}
    ${cssHelper('scroll-snap-margin-right', styling.scrollSnapMarginRight)}
    ${cssHelper('scroll-snap-margin-top', styling.scrollSnapMarginTop)}
    ${cssHelper('scroll-snap-stop', styling.scrollSnapStop)}
    ${cssHelper('scroll-snap-type', styling.scrollSnapType)}
    ${cssHelper('scrollbar-color', styling.scrollbarColor)}
    ${cssHelper('scrollbar-gutter', styling.scrollbarGutter)}
    ${cssHelper('scrollbar-width', styling.scrollbarWidth)}
    ${cssHelper('shape-image-threshold', styling.shapeImageThreshold)}
    ${cssHelper('shape-margin', styling.shapeMargin)}
    ${cssHelper('shape-outside', styling.shapeOutside)}
    ${cssHelper('tab-size', styling.tabSize)}
    ${cssHelper('table-layout', styling.tableLayout)}
    ${cssHelper('text-align', styling.textAlign)}
    ${cssHelper('text-align-last', styling.textAlignLast)}
    ${cssHelper('text-combine-upright', styling.textCombineUpright)}
    ${cssHelper('text-decoration-color', styling.textDecorationColor)}
    ${cssHelper('text-decoration-line', styling.textDecorationLine)}
    ${cssHelper('text-decoration-skip', styling.textDecorationSkip)}
    ${cssHelper('text-decoration-skip-ink', styling.textDecorationSkipInk)}
    ${cssHelper('text-decoration-style', styling.textDecorationStyle)}
    ${cssHelper('text-decoration-thickness', styling.textDecorationThickness)}
    ${cssHelper('text-decoration-width', styling.textDecorationWidth)}
    ${cssHelper('text-emphasis-color', styling.textEmphasisColor)}
    ${cssHelper('text-emphasis-position', styling.textEmphasisPosition)}
    ${cssHelper('text-emphasis-style', styling.textEmphasisStyle)}
    ${cssHelper('text-indent', styling.textIndent)}
    ${cssHelper('text-justify', styling.textJustify)}
    ${cssHelper('text-orientation', styling.textOrientation)}
    ${cssHelper('text-overflow', styling.textOverflow)}
    ${cssHelper('text-rendering', styling.textRendering)}
    ${cssHelper('text-shadow', styling.textShadow)}
    ${cssHelper('text-size-adjust', styling.textSizeAdjust)}
    ${cssHelper('text-transform', styling.textTransform)}
    ${cssHelper('text-underline-offset', styling.textUnderlineOffset)}
    ${cssHelper('text-underline-position', styling.textUnderlinePosition)}
    ${cssHelper('top', styling.top)}
    ${cssHelper('touch-action', styling.touchAction)}
    ${cssHelper('transform', styling.transform)}
    ${cssHelper('transform-box', styling.transformBox)}
    ${cssHelper('transform-origin', styling.transformOrigin)}
    ${cssHelper('transform-style', styling.transformStyle)}
    ${cssHelper('transition-delay', styling.transitionDelay)}
    ${cssHelper('transition-duration', styling.transitionDuration)}
    ${cssHelper('transition-property', styling.transitionProperty)}
    ${cssHelper('transition-timing-function', styling.transitionTimingFunction)}
    ${cssHelper('translate', styling.translate)}
    ${cssHelper('unicode-bidi', styling.unicodeBidi)}
    ${cssHelper('user-select', styling.userSelect)}
    ${cssHelper('vertical-align', styling.verticalAlign)}
    ${cssHelper('visibility', styling.visibility)}
    ${cssHelper('white-space', styling.whiteSpace)}
    ${cssHelper('widows', styling.widows)}
    ${cssHelper('width', styling.width)}
    ${cssHelper('will-change', styling.willChange)}
    ${cssHelper('word-break', styling.wordBreak)}
    ${cssHelper('word-spacing', styling.wordSpacing)}
    ${cssHelper('word-wrap', styling.wordWrap)}
    ${cssHelper('writing-mode', styling.writingMode)}
    ${cssHelper('z-index', styling.zIndex)}
    ${cssHelper('zoom', styling.zoom)}
    ${cssHelper('all', styling.all)}
    ${cssHelper('animation', styling.animation)}
    ${cssHelper('background', styling.background)}
    ${cssHelper('background-position', styling.backgroundPosition)}
    ${cssHelper('border', styling.border)}
    ${cssHelper('border-block', styling.borderBlock)}
    ${cssHelper('border-block-end', styling.borderBlockEnd)}
    ${cssHelper('border-block-start', styling.borderBlockStart)}
    ${cssHelper('border-bottom', styling.borderBottom)}
    ${cssHelper('border-color', styling.borderColor)}
    ${cssHelper('border-image', styling.borderImage)}
    ${cssHelper('border-inline', styling.borderInline)}
    ${cssHelper('border-inline-end', styling.borderInlineEnd)}
    ${cssHelper('border-inline-start', styling.borderInlineStart)}
    ${cssHelper('border-left', styling.borderLeft)}
    ${cssHelper('border-radius', styling.borderRadius)}
    ${cssHelper('border-right', styling.borderRight)}
    ${cssHelper('border-style', styling.borderStyle)}
    ${cssHelper('border-top', styling.borderTop)}
    ${cssHelper('border-width', styling.borderWidth)}
    ${cssHelper('column-rule', styling.columnRule)}
    ${cssHelper('columns', styling.columns)}
    ${cssHelper('flex', styling.flex)}
    ${cssHelper('flex-flow', styling.flexFlow)}
    ${cssHelper('font', styling.font)}
    ${cssHelper('gap', styling.gap)}
    ${cssHelper('grid', styling.grid)}
    ${cssHelper('grid-area', styling.gridArea)}
    ${cssHelper('grid-column', styling.gridColumn)}
    ${cssHelper('grid-row', styling.gridRow)}
    ${cssHelper('grid-template', styling.gridTemplate)}
    ${cssHelper('line-clamp', styling.lineClamp)}
    ${cssHelper('list-style', styling.listStyle)}
    ${cssHelper('margin', styling.margin)}
    ${cssHelper('mask', styling.mask)}
    ${cssHelper('mask-border', styling.maskBorder)}
    ${cssHelper('motion', styling.motion)}
    ${cssHelper('offset', styling.offset)}
    ${cssHelper('outline', styling.outline)}
    ${cssHelper('overflow', styling.overflow)}
    ${cssHelper('overscroll-behavior', styling.overscrollBehavior)}
    ${cssHelper('padding', styling.padding)}
    ${cssHelper('place-items', styling.placeItems)}
    ${cssHelper('place-self', styling.placeSelf)}
    ${cssHelper('text-decoration', styling.textDecoration)}
    ${cssHelper('text-emphasis', styling.textEmphasis)}
    ${cssHelper('transition', styling.transition)}
    ${cssHelper('alignment-baseline', styling.alignmentBaseline)}
    ${cssHelper('baseline-shift', styling.baselineShift)}
    ${cssHelper('clip-rule', styling.clipRule)}
    ${cssHelper('color-interpolation', styling.colorInterpolation)}
    ${cssHelper('color-rendering', styling.colorRendering)}
    ${cssHelper('dominant-baseline', styling.dominantBaseline)}
    ${cssHelper('fill', styling.fill)}
    ${cssHelper('fill-opacity', styling.fillOpacity)}
    ${cssHelper('fill-rule', styling.fillRule)}
    ${cssHelper('flood-color', styling.floodColor)}
    ${cssHelper('flood-opacity', styling.floodOpacity)}
    ${cssHelper('glyph-orientation-vertical', styling.glyphOrientationVertical)}
    ${cssHelper('lighting-color', styling.lightingColor)}
    ${cssHelper('marker', styling.marker)}
    ${cssHelper('marker-end', styling.markerEnd)}
    ${cssHelper('marker-mid', styling.markerMid)}
    ${cssHelper('marker-start', styling.markerStart)}
    ${cssHelper('stop-color', styling.stopColor)}
    ${cssHelper('stop-opacity', styling.stopOpacity)}
    ${cssHelper('stroke', styling.stroke)}
    ${cssHelper('stroke-dasharray', styling.strokeDasharray)}
    ${cssHelper('stroke-dashoffset', styling.strokeDashoffset)}
    ${cssHelper('stroke-linecap', styling.strokeLinecap)}
    ${cssHelper('stroke-linejoin', styling.strokeLinejoin)}
    ${cssHelper('stroke-miterlimit', styling.strokeMiterlimit)}
    ${cssHelper('stroke-opacity', styling.strokeOpacity)}
    ${cssHelper('stroke-width', styling.strokeWidth)}
    ${cssHelper('text-anchor', styling.textAnchor)}
    ${cssHelper('vector-effect', styling.vectorEffect)}
    ${cssHelper('-moz-animation', styling.MozAnimation)}
    ${cssHelper('-moz-border-image', styling.MozBorderImage)}
    ${cssHelper('-moz-column-rule', styling.MozColumnRule)}
    ${cssHelper('-moz-columns', styling.MozColumns)}
    ${cssHelper('-moz-transition', styling.MozTransition)}
    ${cssHelper('-ms-content-zoom-limit', styling.msContentZoomLimit)}
    ${cssHelper('-ms-content-zoom-snap', styling.msContentZoomSnap)}
    ${cssHelper('-ms-flex', styling.msFlex)}
    ${cssHelper('-ms-scroll-limit', styling.msScrollLimit)}
    ${cssHelper('-ms-scroll-snap-x', styling.msScrollSnapX)}
    ${cssHelper('-ms-scroll-snap-y', styling.msScrollSnapY)}
    ${cssHelper('-ms-transition', styling.msTransition)}
    ${cssHelper('-webkit-animation', styling.WebkitAnimation)}
    ${cssHelper('-webkit-border-before', styling.WebkitBorderBefore)}
    ${cssHelper('-webkit-border-image', styling.WebkitBorderImage)}
    ${cssHelper('-webkit-border-radius', styling.WebkitBorderRadius)}
    ${cssHelper('-webkit-column-rule', styling.WebkitColumnRule)}
    ${cssHelper('-webkit-columns', styling.WebkitColumns)}
    ${cssHelper('-webkit-flex', styling.WebkitFlex)}
    ${cssHelper('-webkit-flex-flow', styling.WebkitFlexFlow)}
    ${cssHelper('-webkit-mask', styling.WebkitMask)}
    ${cssHelper('-webkit-mask-box-image', styling.WebkitMaskBoxImage)}
    ${cssHelper('-webkit-text-emphasis', styling.WebkitTextEmphasis)}
    ${cssHelper('-webkit-text-stroke', styling.WebkitTextStroke)}
    ${cssHelper('-webkit-transition', styling.WebkitTransition)}
    ${cssHelper('-moz-animation-delay', styling.MozAnimationDelay)}
    ${cssHelper('-moz-animation-direction', styling.MozAnimationDirection)}
    ${cssHelper('-moz-animation-duration', styling.MozAnimationDuration)}
    ${cssHelper('-moz-animation-fill-mode', styling.MozAnimationFillMode)}
    ${cssHelper('-moz-animation-iteration-count', styling.MozAnimationIterationCount)}
    ${cssHelper('-moz-animation-name', styling.MozAnimationName)}
    ${cssHelper('-moz-animation-play-state', styling.MozAnimationPlayState)}
    ${cssHelper('-moz-animation-timing-function', styling.MozAnimationTimingFunction)}
    ${cssHelper('-moz-appearance', styling.MozAppearance)}
    ${cssHelper('-moz-backface-visibility', styling.MozBackfaceVisibility)}
    ${cssHelper('-moz-border-bottom-colors', styling.MozBorderBottomColors)}
    ${cssHelper('-moz-border-end-color', styling.MozBorderEndColor)}
    ${cssHelper('-moz-border-end-style', styling.MozBorderEndStyle)}
    ${cssHelper('-moz-border-end-width', styling.MozBorderEndWidth)}
    ${cssHelper('-moz-border-left-colors', styling.MozBorderLeftColors)}
    ${cssHelper('-moz-border-right-colors', styling.MozBorderRightColors)}
    ${cssHelper('-moz-border-start-color', styling.MozBorderStartColor)}
    ${cssHelper('-moz-border-start-style', styling.MozBorderStartStyle)}
    ${cssHelper('-moz-border-top-colors', styling.MozBorderTopColors)}
    ${cssHelper('-moz-box-sizing', styling.MozBoxSizing)}
    ${cssHelper('-moz-column-count', styling.MozColumnCount)}
    ${cssHelper('-moz-column-fill', styling.MozColumnFill)}
    ${cssHelper('-moz-column-gap', styling.MozColumnGap)}
    ${cssHelper('-moz-column-rule-color', styling.MozColumnRuleColor)}
    ${cssHelper('-moz-column-rule-style', styling.MozColumnRuleStyle)}
    ${cssHelper('-moz-column-rule-width', styling.MozColumnRuleWidth)}
    ${cssHelper('-moz-column-width', styling.MozColumnWidth)}
    ${cssHelper('-moz-context-properties', styling.MozContextProperties)}
    ${cssHelper('-moz-font-feature-settings', styling.MozFontFeatureSettings)}
    ${cssHelper('-moz-font-language-override', styling.MozFontLanguageOverride)}
    ${cssHelper('-moz-hyphens', styling.MozHyphens)}
    ${cssHelper('-moz-image-region', styling.MozImageRegion)}
    ${cssHelper('-moz-margin-end', styling.MozMarginEnd)}
    ${cssHelper('-moz-margin-start', styling.MozMarginStart)}
    ${cssHelper('-moz-orient', styling.MozOrient)}
    ${cssHelper('-moz-osx-font-smoothing', styling.MozOsxFontSmoothing)}
    ${cssHelper('-moz-padding-end', styling.MozPaddingEnd)}
    ${cssHelper('-moz-padding-start', styling.MozPaddingStart)}
    ${cssHelper('-moz-perspective', styling.MozPerspective)}
    ${cssHelper('-moz-perspective-origin', styling.MozPerspectiveOrigin)}
    ${cssHelper('-moz-stack-sizing', styling.MozStackSizing)}
    ${cssHelper('-moz-tab-size', styling.MozTabSize)}
    ${cssHelper('-moz-text-blink', styling.MozTextBlink)}
    ${cssHelper('-moz-text-size-adjust', styling.MozTextSizeAdjust)}
    ${cssHelper('-moz-transform-origin', styling.MozTransformOrigin)}
    ${cssHelper('-moz-transform-style', styling.MozTransformStyle)}
    ${cssHelper('-moz-transition-delay', styling.MozTransitionDelay)}
    ${cssHelper('-moz-transition-duration', styling.MozTransitionDuration)}
    ${cssHelper('-moz-transition-property', styling.MozTransitionProperty)}
    ${cssHelper('-moz-transition-timing-function', styling.MozTransitionTimingFunction)}
    ${cssHelper('-moz-user-focus', styling.MozUserFocus)}
    ${cssHelper('-moz-user-modify', styling.MozUserModify)}
    ${cssHelper('-moz-user-select', styling.MozUserSelect)}
    ${cssHelper('-moz-window-dragging', styling.MozWindowDragging)}
    ${cssHelper('-moz-window-shadow', styling.MozWindowShadow)}
    ${cssHelper('-ms-accelerator', styling.msAccelerator)}
    ${cssHelper('-ms-align-self', styling.msAlignSelf)}
    ${cssHelper('-ms-block-progression', styling.msBlockProgression)}
    ${cssHelper('-ms-content-zoom-chaining', styling.msContentZoomChaining)}
    ${cssHelper('-ms-content-zoom-limit-max', styling.msContentZoomLimitMax)}
    ${cssHelper('-ms-content-zoom-limit-min', styling.msContentZoomLimitMin)}
    ${cssHelper('-ms-content-zoom-snap-points', styling.msContentZoomSnapPoints)}
    ${cssHelper('-ms-content-zoom-snap-type', styling.msContentZoomSnapType)}
    ${cssHelper('-ms-content-zooming', styling.msContentZooming)}
    ${cssHelper('-ms-filter', styling.msFilter)}
    ${cssHelper('-ms-flex-direction', styling.msFlexDirection)}
    ${cssHelper('-ms-flex-positive', styling.msFlexPositive)}
    ${cssHelper('-ms-flow-from', styling.msFlowFrom)}
    ${cssHelper('-ms-flow-into', styling.msFlowInto)}
    ${cssHelper('-ms-grid-columns', styling.msGridColumns)}
    ${cssHelper('-ms-grid-rows', styling.msGridRows)}
    ${cssHelper('-ms-high-contrast-adjust', styling.msHighContrastAdjust)}
    ${cssHelper('-ms-hyphenate-limit-chars', styling.msHyphenateLimitChars)}
    ${cssHelper('-ms-hyphenate-limit-lines', styling.msHyphenateLimitLines)}
    ${cssHelper('-ms-hyphenate-limit-zone', styling.msHyphenateLimitZone)}
    ${cssHelper('-ms-hyphens', styling.msHyphens)}
    ${cssHelper('-ms-ime-align', styling.msImeAlign)}
    ${cssHelper('-ms-justify-self', styling.msJustifySelf)}
    ${cssHelper('-ms-line-break', styling.msLineBreak)}
    ${cssHelper('-ms-order', styling.msOrder)}
    ${cssHelper('-ms-overflow-style', styling.msOverflowStyle)}
    ${cssHelper('-ms-overflow-x', styling.msOverflowX)}
    ${cssHelper('-ms-overflow-y', styling.msOverflowY)}
    ${cssHelper('-ms-scroll-chaining', styling.msScrollChaining)}
    ${cssHelper('-ms-scroll-limit-x-max', styling.msScrollLimitXMax)}
    ${cssHelper('-ms-scroll-limit-x-min', styling.msScrollLimitXMin)}
    ${cssHelper('-ms-scroll-limit-y-max', styling.msScrollLimitYMax)}
    ${cssHelper('-ms-scroll-limit-y-min', styling.msScrollLimitYMin)}
    ${cssHelper('-ms-scroll-rails', styling.msScrollRails)}
    ${cssHelper('-ms-scroll-snap-points-x', styling.msScrollSnapPointsX)}
    ${cssHelper('-ms-scroll-snap-points-y', styling.msScrollSnapPointsY)}
    ${cssHelper('-ms-scroll-snap-type', styling.msScrollSnapType)}
    ${cssHelper('-ms-scroll-translation', styling.msScrollTranslation)}
    ${cssHelper('-ms-scrollbar-3-dlight-color', styling.msScrollbar3dlightColor)}
    ${cssHelper('-ms-scrollbar-arrow-color', styling.msScrollbarArrowColor)}
    ${cssHelper('-ms-scrollbar-base-color', styling.msScrollbarBaseColor)}
    ${cssHelper('-ms-scrollbar-darkshadow-color', styling.msScrollbarDarkshadowColor)}
    ${cssHelper('-ms-scrollbar-face-color', styling.msScrollbarFaceColor)}
    ${cssHelper('-ms-scrollbar-highlight-color', styling.msScrollbarHighlightColor)}
    ${cssHelper('-ms-scrollbar-shadow-color', styling.msScrollbarShadowColor)}
    ${cssHelper('-ms-text-autospace', styling.msTextAutospace)}
    ${cssHelper('-ms-text-combine-horizontal', styling.msTextCombineHorizontal)}
    ${cssHelper('-ms-text-overflow', styling.msTextOverflow)}
    ${cssHelper('-ms-touch-action', styling.msTouchAction)}
    ${cssHelper('-ms-touch-select', styling.msTouchSelect)}
    ${cssHelper('-ms-transform', styling.msTransform)}
    ${cssHelper('-ms-transform-origin', styling.msTransformOrigin)}
    ${cssHelper('-ms-transition-delay', styling.msTransitionDelay)}
    ${cssHelper('-ms-transition-duration', styling.msTransitionDuration)}
    ${cssHelper('-ms-transition-property', styling.msTransitionProperty)}
    ${cssHelper('-ms-transition-timing-function', styling.msTransitionTimingFunction)}
    ${cssHelper('-ms-user-select', styling.msUserSelect)}
    ${cssHelper('-ms-word-break', styling.msWordBreak)}
    ${cssHelper('-ms-wrap-flow', styling.msWrapFlow)}
    ${cssHelper('-ms-wrap-margin', styling.msWrapMargin)}
    ${cssHelper('-ms-wrap-through', styling.msWrapThrough)}
    ${cssHelper('-ms-writing-mode', styling.msWritingMode)}
    ${cssHelper('-webkit-align-content', styling.WebkitAlignContent)}
    ${cssHelper('-webkit-align-items', styling.WebkitAlignItems)}
    ${cssHelper('-webkit-align-self', styling.WebkitAlignSelf)}
    ${cssHelper('-webkit-animation-delay', styling.WebkitAnimationDelay)}
    ${cssHelper('-webkit-animation-direction', styling.WebkitAnimationDirection)}
    ${cssHelper('-webkit-animation-duration', styling.WebkitAnimationDuration)}
    ${cssHelper('-webkit-animation-fill-mode', styling.WebkitAnimationFillMode)}
    ${cssHelper('-webkit-animation-iteration-count', styling.WebkitAnimationIterationCount)}
    ${cssHelper('-webkit-animation-name', styling.WebkitAnimationName)}
    ${cssHelper('-webkit-animation-play-state', styling.WebkitAnimationPlayState)}
    ${cssHelper('-webkit-animation-timing-function', styling.WebkitAnimationTimingFunction)}
    ${cssHelper('-webkit-appearance', styling.WebkitAppearance)}
    ${cssHelper('-webkit-backdrop-filter', styling.WebkitBackdropFilter)}
    ${cssHelper('-webkit-backface-visibility', styling.WebkitBackfaceVisibility)}
    ${cssHelper('-webkit-background-clip', styling.WebkitBackgroundClip)}
    ${cssHelper('-webkit-background-origin', styling.WebkitBackgroundOrigin)}
    ${cssHelper('-webkit-background-size', styling.WebkitBackgroundSize)}
    ${cssHelper('-webkit-border-before-color', styling.WebkitBorderBeforeColor)}
    ${cssHelper('-webkit-border-before-style', styling.WebkitBorderBeforeStyle)}
    ${cssHelper('-webkit-border-before-width', styling.WebkitBorderBeforeWidth)}
    ${cssHelper('-webkit-border-bottom-left-radius', styling.WebkitBorderBottomLeftRadius)}
    ${cssHelper('-webkit-border-bottom-right-radius', styling.WebkitBorderBottomRightRadius)}
    ${cssHelper('-webkit-border-image-slice', styling.WebkitBorderImageSlice)}
    ${cssHelper('-webkit-border-top-left-radius', styling.WebkitBorderTopLeftRadius)}
    ${cssHelper('-webkit-border-top-right-radius', styling.WebkitBorderTopRightRadius)}
    ${cssHelper('-webkit-box-decoration-break', styling.WebkitBoxDecorationBreak)}
    ${cssHelper('-webkit-box-reflect', styling.WebkitBoxReflect)}
    ${cssHelper('-webkit-box-shadow', styling.WebkitBoxShadow)}
    ${cssHelper('-webkit-box-sizing', styling.WebkitBoxSizing)}
    ${cssHelper('-webkit-clip-path', styling.WebkitClipPath)}
    ${cssHelper('-webkit-column-count', styling.WebkitColumnCount)}
    ${cssHelper('-webkit-column-fill', styling.WebkitColumnFill)}
    ${cssHelper('-webkit-column-gap', styling.WebkitColumnGap)}
    ${cssHelper('-webkit-column-rule-color', styling.WebkitColumnRuleColor)}
    ${cssHelper('-webkit-column-rule-style', styling.WebkitColumnRuleStyle)}
    ${cssHelper('-webkit-column-rule-width', styling.WebkitColumnRuleWidth)}
    ${cssHelper('-webkit-column-span', styling.WebkitColumnSpan)}
    ${cssHelper('-webkit-column-width', styling.WebkitColumnWidth)}
    ${cssHelper('-webkit-filter', styling.WebkitFilter)}
    ${cssHelper('-webkit-flex-basis', styling.WebkitFlexBasis)}
    ${cssHelper('-webkit-flex-direction', styling.WebkitFlexDirection)}
    ${cssHelper('-webkit-flex-grow', styling.WebkitFlexGrow)}
    ${cssHelper('-webkit-flex-shrink', styling.WebkitFlexShrink)}
    ${cssHelper('-webkit-flex-wrap', styling.WebkitFlexWrap)}
    ${cssHelper('-webkit-font-feature-settings', styling.WebkitFontFeatureSettings)}
    ${cssHelper('-webkit-font-kerning', styling.WebkitFontKerning)}
    ${cssHelper('-webkit-font-smoothing', styling.WebkitFontSmoothing)}
    ${cssHelper('-webkit-font-variant-ligatures', styling.WebkitFontVariantLigatures)}
    ${cssHelper('-webkit-hyphens', styling.WebkitHyphens)}
    ${cssHelper('-webkit-justify-content', styling.WebkitJustifyContent)}
    ${cssHelper('-webkit-line-break', styling.WebkitLineBreak)}
    ${cssHelper('-webkit-line-clamp', styling.WebkitLineClamp)}
    ${cssHelper('-webkit-margin-end', styling.WebkitMarginEnd)}
    ${cssHelper('-webkit-margin-start', styling.WebkitMarginStart)}
    ${cssHelper('-webkit-mask-attachment', styling.WebkitMaskAttachment)}
    ${cssHelper('-webkit-mask-box-image-outset', styling.WebkitMaskBoxImageOutset)}
    ${cssHelper('-webkit-mask-box-image-repeat', styling.WebkitMaskBoxImageRepeat)}
    ${cssHelper('-webkit-mask-box-image-slice', styling.WebkitMaskBoxImageSlice)}
    ${cssHelper('-webkit-mask-box-image-source', styling.WebkitMaskBoxImageSource)}
    ${cssHelper('-webkit-mask-box-image-width', styling.WebkitMaskBoxImageWidth)}
    ${cssHelper('-webkit-mask-clip', styling.WebkitMaskClip)}
    ${cssHelper('-webkit-mask-composite', styling.WebkitMaskComposite)}
    ${cssHelper('-webkit-mask-image', styling.WebkitMaskImage)}
    ${cssHelper('-webkit-mask-origin', styling.WebkitMaskOrigin)}
    ${cssHelper('-webkit-mask-position', styling.WebkitMaskPosition)}
    ${cssHelper('-webkit-mask-position-x', styling.WebkitMaskPositionX)}
    ${cssHelper('-webkit-mask-position-y', styling.WebkitMaskPositionY)}
    ${cssHelper('-webkit-mask-repeat', styling.WebkitMaskRepeat)}
    ${cssHelper('-webkit-mask-repeat-x', styling.WebkitMaskRepeatX)}
    ${cssHelper('-webkit-mask-repeat-y', styling.WebkitMaskRepeatY)}
    ${cssHelper('-webkit-mask-size', styling.WebkitMaskSize)}
    ${cssHelper('-webkit-max-inline-size', styling.WebkitMaxInlineSize)}
    ${cssHelper('-webkit-order', styling.WebkitOrder)}
    ${cssHelper('-webkit-overflow-scrolling', styling.WebkitOverflowScrolling)}
    ${cssHelper('-webkit-padding-end', styling.WebkitPaddingEnd)}
    ${cssHelper('-webkit-padding-start', styling.WebkitPaddingStart)}
    ${cssHelper('-webkit-perspective', styling.WebkitPerspective)}
    ${cssHelper('-webkit-perspective-origin', styling.WebkitPerspectiveOrigin)}
    ${cssHelper('-webkit-print-color-adjust', styling.WebkitPrintColorAdjust)}
    ${cssHelper('-webkit-ruby-position', styling.WebkitRubyPosition)}
    ${cssHelper('-webkit-scroll-snap-type', styling.WebkitScrollSnapType)}
    ${cssHelper('-webkit-shape-margin', styling.WebkitShapeMargin)}
    ${cssHelper('-webkit-tap-highlight-color', styling.WebkitTapHighlightColor)}
    ${cssHelper('-webkit-text-combine', styling.WebkitTextCombine)}
    ${cssHelper('-webkit-text-decoration-color', styling.WebkitTextDecorationColor)}
    ${cssHelper('-webkit-text-decoration-line', styling.WebkitTextDecorationLine)}
    ${cssHelper('-webkit-text-decoration-skip', styling.WebkitTextDecorationSkip)}
    ${cssHelper('-webkit-text-decoration-style', styling.WebkitTextDecorationStyle)}
    ${cssHelper('-webkit-text-emphasis-color', styling.WebkitTextEmphasisColor)}
    ${cssHelper('-webkit-text-emphasis-position', styling.WebkitTextEmphasisPosition)}
    ${cssHelper('-webkit-text-emphasis-style', styling.WebkitTextEmphasisStyle)}
    ${cssHelper('-webkit-text-fill-color', styling.WebkitTextFillColor)}
    ${cssHelper('-webkit-text-orientation', styling.WebkitTextOrientation)}
    ${cssHelper('-webkit-text-size-adjust', styling.WebkitTextSizeAdjust)}
    ${cssHelper('-webkit-text-stroke-color', styling.WebkitTextStrokeColor)}
    ${cssHelper('-webkit-text-stroke-width', styling.WebkitTextStrokeWidth)}
    ${cssHelper('-webkit-text-underline-position', styling.WebkitTextUnderlinePosition)}
    ${cssHelper('-webkit-touch-callout', styling.WebkitTouchCallout)}
    ${cssHelper('-webkit-transform', styling.WebkitTransform)}
    ${cssHelper('-webkit-transform-origin', styling.WebkitTransformOrigin)}
    ${cssHelper('-webkit-transform-style', styling.WebkitTransformStyle)}
    ${cssHelper('-webkit-transition-delay', styling.WebkitTransitionDelay)}
    ${cssHelper('-webkit-transition-duration', styling.WebkitTransitionDuration)}
    ${cssHelper('-webkit-transition-property', styling.WebkitTransitionProperty)}
    ${cssHelper('-webkit-transition-timing-function', styling.WebkitTransitionTimingFunction)}
    ${cssHelper('-webkit-user-modify', styling.WebkitUserModify)}
    ${cssHelper('-webkit-user-select', styling.WebkitUserSelect)}
    ${cssHelper('-webkit-writing-mode', styling.WebkitWritingMode)}
    ${cssHelper('azimuth', styling.azimuth)}
    ${cssHelper('box-align', styling.boxAlign)}
    ${cssHelper('box-direction', styling.boxDirection)}
    ${cssHelper('box-flex', styling.boxFlex)}
    ${cssHelper('box-flex-group', styling.boxFlexGroup)}
    ${cssHelper('box-lines', styling.boxLines)}
    ${cssHelper('box-ordinal-group', styling.boxOrdinalGroup)}
    ${cssHelper('box-orient', styling.boxOrient)}
    ${cssHelper('box-pack', styling.boxPack)}
    ${cssHelper('clip', styling.clip)}
    ${cssHelper('font-variant-alternates', styling.fontVariantAlternates)}
    ${cssHelper('grid-column-gap', styling.gridColumnGap)}
    ${cssHelper('grid-gap', styling.gridGap)}
    ${cssHelper('grid-row-gap', styling.gridRowGap)}
    ${cssHelper('ime-mode', styling.imeMode)}
    ${cssHelper('offset-block', styling.offsetBlock)}
    ${cssHelper('offset-block-end', styling.offsetBlockEnd)}
    ${cssHelper('offset-block-start', styling.offsetBlockStart)}
    ${cssHelper('offset-inline', styling.offsetInline)}
    ${cssHelper('offset-inline-end', styling.offsetInlineEnd)}
    ${cssHelper('offset-inline-start', styling.offsetInlineStart)}
    ${cssHelper('scroll-snap-coordinate', styling.scrollSnapCoordinate)}
    ${cssHelper('scroll-snap-destination', styling.scrollSnapDestination)}
    ${cssHelper('scroll-snap-points-x', styling.scrollSnapPointsX)}
    ${cssHelper('scroll-snap-points-y', styling.scrollSnapPointsY)}
    ${cssHelper('scroll-snap-type-x', styling.scrollSnapTypeX)}
    ${cssHelper('scroll-snap-type-y', styling.scrollSnapTypeY)}
    ${cssHelper('scrollbar-track-color', styling.scrollbarTrackColor)}
    ${cssHelper('-khtml-box-align', styling.KhtmlBoxAlign)}
    ${cssHelper('-khtml-box-direction', styling.KhtmlBoxDirection)}
    ${cssHelper('-khtml-box-flex', styling.KhtmlBoxFlex)}
    ${cssHelper('-khtml-box-flex-group', styling.KhtmlBoxFlexGroup)}
    ${cssHelper('-khtml-box-lines', styling.KhtmlBoxLines)}
    ${cssHelper('-khtml-box-ordinal-group', styling.KhtmlBoxOrdinalGroup)}
    ${cssHelper('-khtml-box-orient', styling.KhtmlBoxOrient)}
    ${cssHelper('-khtml-box-pack', styling.KhtmlBoxPack)}
    ${cssHelper('-khtml-line-break', styling.KhtmlLineBreak)}
    ${cssHelper('-khtml-opacity', styling.KhtmlOpacity)}
    ${cssHelper('-khtml-user-select', styling.KhtmlUserSelect)}
    ${cssHelper('-moz-background-clip', styling.MozBackgroundClip)}
    ${cssHelper('-moz-background-inline-policy', styling.MozBackgroundInlinePolicy)}
    ${cssHelper('-moz-background-origin', styling.MozBackgroundOrigin)}
    ${cssHelper('-moz-background-size', styling.MozBackgroundSize)}
    ${cssHelper('-moz-binding', styling.MozBinding)}
    ${cssHelper('-moz-border-radius', styling.MozBorderRadius)}
    ${cssHelper('-moz-border-radius-bottomleft', styling.MozBorderRadiusBottomleft)}
    ${cssHelper('-moz-border-radius-bottomright', styling.MozBorderRadiusBottomright)}
    ${cssHelper('-moz-border-radius-topleft', styling.MozBorderRadiusTopleft)}
    ${cssHelper('-moz-border-radius-topright', styling.MozBorderRadiusTopright)}
    ${cssHelper('-moz-box-align', styling.MozBoxAlign)}
    ${cssHelper('-moz-box-direction', styling.MozBoxDirection)}
    ${cssHelper('-moz-box-flex', styling.MozBoxFlex)}
    ${cssHelper('-moz-box-ordinal-group', styling.MozBoxOrdinalGroup)}
    ${cssHelper('-moz-box-orient', styling.MozBoxOrient)}
    ${cssHelper('-moz-box-pack', styling.MozBoxPack)}
    ${cssHelper('-moz-box-shadow', styling.MozBoxShadow)}
    ${cssHelper('-moz-float-edge', styling.MozFloatEdge)}
    ${cssHelper('-moz-force-broken-image-icon', styling.MozForceBrokenImageIcon)}
    ${cssHelper('-moz-opacity', styling.MozOpacity)}
    ${cssHelper('-moz-outline', styling.MozOutline)}
    ${cssHelper('-moz-outline-color', styling.MozOutlineColor)}
    ${cssHelper('-moz-outline-radius', styling.MozOutlineRadius)}
    ${cssHelper('-moz-outline-radius-bottomleft', styling.MozOutlineRadiusBottomleft)}
    ${cssHelper('-moz-outline-radius-bottomright', styling.MozOutlineRadiusBottomright)}
    ${cssHelper('-moz-outline-radius-topleft', styling.MozOutlineRadiusTopleft)}
    ${cssHelper('-moz-outline-radius-topright', styling.MozOutlineRadiusTopright)}
    ${cssHelper('-moz-outline-style', styling.MozOutlineStyle)}
    ${cssHelper('-moz-outline-width', styling.MozOutlineWidth)}
    ${cssHelper('-moz-text-align-last', styling.MozTextAlignLast)}
    ${cssHelper('-moz-text-decoration-color', styling.MozTextDecorationColor)}
    ${cssHelper('-moz-text-decoration-line', styling.MozTextDecorationLine)}
    ${cssHelper('-moz-text-decoration-style', styling.MozTextDecorationStyle)}
    ${cssHelper('-moz-user-input', styling.MozUserInput)}
    ${cssHelper('-ms-ime-mode', styling.msImeMode)}
    ${cssHelper('-ms-scrollbar-track-color', styling.msScrollbarTrackColor)}
    ${cssHelper('-o-animation', styling.OAnimation)}
    ${cssHelper('-o-animation-delay', styling.OAnimationDelay)}
    ${cssHelper('-o-animation-direction', styling.OAnimationDirection)}
    ${cssHelper('-o-animation-duration', styling.OAnimationDuration)}
    ${cssHelper('-o-animation-fill-mode', styling.OAnimationFillMode)}
    ${cssHelper('-o-animation-iteration-count', styling.OAnimationIterationCount)}
    ${cssHelper('-o-animation-name', styling.OAnimationName)}
    ${cssHelper('-o-animation-play-state', styling.OAnimationPlayState)}
    ${cssHelper('-o-animation-timing-function', styling.OAnimationTimingFunction)}
    ${cssHelper('-o-background-size', styling.OBackgroundSize)}
    ${cssHelper('-o-border-image', styling.OBorderImage)}
    ${cssHelper('-o-object-fit', styling.OObjectFit)}
    ${cssHelper('-o-object-position', styling.OObjectPosition)}
    ${cssHelper('-o-tab-size', styling.OTabSize)}
    ${cssHelper('-o-text-overflow', styling.OTextOverflow)}
    ${cssHelper('-o-transform', styling.OTransform)}
    ${cssHelper('-o-transform-origin', styling.OTransformOrigin)}
    ${cssHelper('-o-transition', styling.OTransition)}
    ${cssHelper('-o-transition-delay', styling.OTransitionDelay)}
    ${cssHelper('-o-transition-duration', styling.OTransitionDuration)}
    ${cssHelper('-o-transition-property', styling.OTransitionProperty)}
    ${cssHelper('-o-transition-timing-function', styling.OTransitionTimingFunction)}
    ${cssHelper('-webkit-box-align', styling.WebkitBoxAlign)}
    ${cssHelper('-webkit-box-direction', styling.WebkitBoxDirection)}
    ${cssHelper('-webkit-box-flex', styling.WebkitBoxFlex)}
    ${cssHelper('-webkit-box-flex-group', styling.WebkitBoxFlexGroup)}
    ${cssHelper('-webkit-box-lines', styling.WebkitBoxLines)}
    ${cssHelper('-webkit-box-ordinal-group', styling.WebkitBoxOrdinalGroup)}
    ${cssHelper('-webkit-box-orient', styling.WebkitBoxOrient)}
    ${cssHelper('-webkit-box-pack', styling.WebkitBoxPack)}
    ${cssHelper('-webkit-scroll-snap-points-x', styling.WebkitScrollSnapPointsX)}
    ${cssHelper('-webkit-scroll-snap-points-y', styling.WebkitScrollSnapPointsY)}
  `;
}

function createPseudos(pseudos?: PseudosObject) {
  if (!pseudos) return '';

  return `
    ${pseudoHelper(':-moz-any()', pseudos)}
    ${pseudoHelper(':-moz-dir', pseudos)}
    ${pseudoHelper(':-webkit-any()', pseudos)}
    ${pseudoHelper('::cue', pseudos)}
    ${pseudoHelper('::cue-region', pseudos)}
    ${pseudoHelper('::part', pseudos)}
    ${pseudoHelper('::slotted', pseudos)}
    ${pseudoHelper(':dir', pseudos)}
    ${pseudoHelper(':has', pseudos)}
    ${pseudoHelper(':host', pseudos)}
    ${pseudoHelper(':host-context', pseudos)}
    ${pseudoHelper(':is', pseudos)}
    ${pseudoHelper(':lang', pseudos)}
    ${pseudoHelper(':matches()', pseudos)}
    ${pseudoHelper(':not', pseudos)}
    ${pseudoHelper(':nth-child', pseudos)}
    ${pseudoHelper(':nth-last-child', pseudos)}
    ${pseudoHelper(':nth-last-of-type', pseudos)}
    ${pseudoHelper(':nth-of-type', pseudos)}
    ${pseudoHelper(':where', pseudos)}
    ${pseudoHelper(':-khtml-any-link', pseudos)}
    ${pseudoHelper(':-moz-any-link', pseudos)}
    ${pseudoHelper(':-moz-focusring', pseudos)}
    ${pseudoHelper(':-moz-full-screen', pseudos)}
    ${pseudoHelper(':-moz-placeholder', pseudos)}
    ${pseudoHelper(':-moz-read-only', pseudos)}
    ${pseudoHelper(':-moz-read-write', pseudos)}
    ${pseudoHelper(':-moz-ui-invalid', pseudos)}
    ${pseudoHelper(':-moz-ui-valid', pseudos)}
    ${pseudoHelper(':-ms-fullscreen', pseudos)}
    ${pseudoHelper(':-ms-input-placeholder', pseudos)}
    ${pseudoHelper(':-webkit-any-link', pseudos)}
    ${pseudoHelper(':-webkit-full-screen', pseudos)}
    ${pseudoHelper('::-moz-placeholder', pseudos)}
    ${pseudoHelper('::-moz-progress-bar', pseudos)}
    ${pseudoHelper('::-moz-range-progress', pseudos)}
    ${pseudoHelper('::-moz-range-thumb', pseudos)}
    ${pseudoHelper('::-moz-range-track', pseudos)}
    ${pseudoHelper('::-moz-selection', pseudos)}
    ${pseudoHelper('::-ms-backdrop', pseudos)}
    ${pseudoHelper('::-ms-browse', pseudos)}
    ${pseudoHelper('::-ms-check', pseudos)}
    ${pseudoHelper('::-ms-clear', pseudos)}
    ${pseudoHelper('::-ms-expand', pseudos)}
    ${pseudoHelper('::-ms-fill', pseudos)}
    ${pseudoHelper('::-ms-fill-lower', pseudos)}
    ${pseudoHelper('::-ms-fill-upper', pseudos)}
    ${pseudoHelper('::-ms-input-placeholder', pseudos)}
    ${pseudoHelper('::-ms-reveal', pseudos)}
    ${pseudoHelper('::-ms-thumb', pseudos)}
    ${pseudoHelper('::-ms-ticks-after', pseudos)}
    ${pseudoHelper('::-ms-ticks-before', pseudos)}
    ${pseudoHelper('::-ms-tooltip', pseudos)}
    ${pseudoHelper('::-ms-track', pseudos)}
    ${pseudoHelper('::-ms-value', pseudos)}
    ${pseudoHelper('::-webkit-backdrop', pseudos)}
    ${pseudoHelper('::-webkit-input-placeholder', pseudos)}
    ${pseudoHelper('::-webkit-progress-bar', pseudos)}
    ${pseudoHelper('::-webkit-progress-inner-value', pseudos)}
    ${pseudoHelper('::-webkit-progress-value', pseudos)}
    ${pseudoHelper('::-webkit-slider-runnable-track', pseudos)}
    ${pseudoHelper('::-webkit-slider-thumb', pseudos)}
    ${pseudoHelper('::after', pseudos)}
    ${pseudoHelper('::backdrop', pseudos)}
    ${pseudoHelper('::before', pseudos)}
    ${pseudoHelper('::cue', pseudos)}
    ${pseudoHelper('::cue-region', pseudos)}
    ${pseudoHelper('::first-letter', pseudos)}
    ${pseudoHelper('::first-line', pseudos)}
    ${pseudoHelper('::grammar-error', pseudos)}
    ${pseudoHelper('::marker', pseudos)}
    ${pseudoHelper('::placeholder', pseudos)}
    ${pseudoHelper('::selection', pseudos)}
    ${pseudoHelper('::spelling-error', pseudos)}
    ${pseudoHelper('::target-text', pseudos)}
    ${pseudoHelper(':active', pseudos)}
    ${pseudoHelper(':after', pseudos)}
    ${pseudoHelper(':any-link', pseudos)}
    ${pseudoHelper(':before', pseudos)}
    ${pseudoHelper(':blank', pseudos)}
    ${pseudoHelper(':checked', pseudos)}
    ${pseudoHelper(':current', pseudos)}
    ${pseudoHelper(':default', pseudos)}
    ${pseudoHelper(':defined', pseudos)}
    ${pseudoHelper(':disabled', pseudos)}
    ${pseudoHelper(':empty', pseudos)}
    ${pseudoHelper(':enabled', pseudos)}
    ${pseudoHelper(':first', pseudos)}
    ${pseudoHelper(':first-child', pseudos)}
    ${pseudoHelper(':first-letter', pseudos)}
    ${pseudoHelper(':first-line', pseudos)}
    ${pseudoHelper(':first-of-type', pseudos)}
    ${pseudoHelper(':focus', pseudos)}
    ${pseudoHelper(':focus-visible', pseudos)}
    ${pseudoHelper(':focus-within', pseudos)}
    ${pseudoHelper(':fullscreen', pseudos)}
    ${pseudoHelper(':future', pseudos)}
    ${pseudoHelper(':hover', pseudos)}
    ${pseudoHelper(':in-range', pseudos)}
    ${pseudoHelper(':indeterminate', pseudos)}
    ${pseudoHelper(':invalid', pseudos)}
    ${pseudoHelper(':last-child', pseudos)}
    ${pseudoHelper(':last-of-type', pseudos)}
    ${pseudoHelper(':left', pseudos)}
    ${pseudoHelper(':link', pseudos)}
    ${pseudoHelper(':local-link', pseudos)}
    ${pseudoHelper(':nth-col', pseudos)}
    ${pseudoHelper(':nth-last-col', pseudos)}
    ${pseudoHelper(':only-child', pseudos)}
    ${pseudoHelper(':only-of-type', pseudos)}
    ${pseudoHelper(':optional', pseudos)}
    ${pseudoHelper(':out-of-range', pseudos)}
    ${pseudoHelper(':past', pseudos)}
    ${pseudoHelper(':paused', pseudos)}
    ${pseudoHelper(':picture-in-picture', pseudos)}
    ${pseudoHelper(':placeholder-shown', pseudos)}
    ${pseudoHelper(':playing', pseudos)}
    ${pseudoHelper(':read-only', pseudos)}
    ${pseudoHelper(':read-write', pseudos)}
    ${pseudoHelper(':required', pseudos)}
    ${pseudoHelper(':right', pseudos)}
    ${pseudoHelper(':root', pseudos)}
    ${pseudoHelper(':scope', pseudos)}
    ${pseudoHelper(':target', pseudos)}
    ${pseudoHelper(':target-within', pseudos)}
    ${pseudoHelper(':user-invalid', pseudos)}
    ${pseudoHelper(':user-valid', pseudos)}
    ${pseudoHelper(':valid', pseudos)}
    ${pseudoHelper(':visited', pseudos)}
  `;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function cssHelper(name: string, value: any): string {
  if (value) {
    return `${name}: ${value};`;
  }

  return '';
}

function pseudoHelper(name: Pseudos, pseudos: PseudosObject): string {
  const pseudoExists = pseudos[name];

  if (pseudoExists) {
    return `
      &${name} {
        ${createCss(pseudoExists)}
      }
    `;
  }

  return '';
}
